#!/usr/bin/perl -w
#       Copyright (C) 2017 HikariKnight <rshikariknight@gmail.com>
#       and contributors found in the AUTHORS file.
#       Use of this script is governed by a GPL v2 license
#       that can be found in the LICENSE file.
#       Source code and contact info at https://github.com/HikariKnight/runescape

# Use the FindBin module so we can get the scriptname
use FindBin;

# Get the script name
my $scriptname = $FindBin::Script;

# Remove legacy names (and rsu-query)
$scriptname =~ s/rsu-(|query)//;
$scriptname =~ s/-runescape-client/r/;

# If the runescape folder is found
if (-d "/opt/runescape")
{
	# If scriptname is runescape and no parameters are passed
	if ($scriptname =~ /^runescape$/ && "@ARGV" eq '')
	{
		# Run the rsu launcher or fall back to launching runescape directly
		system "/opt/runescape/rsu/rsu-query";
	}
	# Else if scriptname is runescape and parameters are passed and the parameters do not start with - then
	elsif($scriptname =~ /^runescape$/ && "@ARGV" ne '' && "@ARGV" !~ /^-/)
	{
		# Do an rsu-query
		system "/opt/runescape/rsu/rsu-query @ARGV";
	}
	# Else
	else
	{
		# Run the script the user is calling through rsu-query
		system "/opt/runescape/rsu/rsu-query client.launch.$scriptname @ARGV";
	}
}
elsif (-d "/opt/extras.ubuntu.com/rsu-client")
{
	# If scriptname is runescape and no parameters are passed
	if ($scriptname =~ /^runescape$/ && "@ARGV" eq '')
	{
		# Run the rsu launcher or fall back to launching runescape directly
		system "/opt/extras.ubuntu.com/rsu-client/rsu/rsu-query @ARGV";
	}
	# Else if scriptname is runescape and parameters are passed and the parameters do not start with - then
	elsif($scriptname =~ /^runescape$/ && "@ARGV" ne '' && "@ARGV" !~ /^-/)
	{
		# Do an rsu-query
		system "/opt/extras.ubuntu.com/rsu-client/rsu/rsu-query @ARGV";
	}
	# Else
	else
	{
		# Run the script the user is calling through rsu-query
		system "/opt/extras.ubuntu.com/rsu-client/rsu/rsu-query client.launch.$scriptname @ARGV";
	}
}
