#!/usr/bin/perl -w

# Use the FindBin module so we can get the scriptname
use FindBin;

# Get the script name
my $scriptname = $FindBin::Script;

# Remove legacy names (and rsu-query)
$scriptname =~ s/rsu-(|query)//;
$scriptname =~ s/-runescape-client/r/;

# If the runescape folder is found
if (-d "/opt/runescape")
{
	# If scriptname is runescape and no parameters are passed
	if ($scriptname =~ /^runescape$/ && "$ARGV[0]" =~ /(\.|::)/ && "$ARGV[0]" !~ /^-/)
	{
		# Run the rsu launcher or fall back to launching runescape directly
		system "/opt/runescape/rsu/rsu-query @ARGV";
	}
	# Else
	else
	{
		# Run the script the user is calling through rsu-query
		system "/opt/runescape/rsu/rsu-query client.launch.$scriptname @ARGV";
	}
}
elsif (-d "/opt/extras.ubuntu.com/rsu-client")
{
	# If scriptname is runescape and no parameters are passed
	if ($scriptname =~ /^runescape$/ && "$ARGV[0]" =~ /(\.|::)/ && "$ARGV[0]" !~ /^-/)
	{
		# Run the rsu launcher or fall back to launching runescape directly
		system "/opt/extras.ubuntu.com/rsu-client/rsu/rsu-query @ARGV";
	}
	# Else
	else
	{
		# Run the script the user is calling through rsu-query
		system "/opt/extras.ubuntu.com/rsu-client/rsu/rsu-query client.launch.$scriptname @ARGV";
	}
}
