#!/usr/bin/perl -w
#
#    The main script of the rsu-client, this takes care of overhead stuff
#    Copyright (C) 2011-2013  HikariKnight
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
####
# All files(except jagexappletviewer.jar) and modules used by this script
# uses the same license stated above unless something else is specified
# in their header. External commands use their own license
####
# Be strict to avoid messy code
use strict;

# Use FindBin module to get script directory
use FindBin;

# Get script directory
my $cwd = $FindBin::RealBin;
# Get script filename
my $scriptname = $FindBin::Script;
# Detect the current OS
my $OS = "$^O";

# URL for the maclibs download
my $maclib_url = "https://dl.dropbox.com/u/11631899/opensource/Perl/runescape_unix_client/modules/darwin.tar.gz";

# Perl command to launch the rsu-settings script with
my $perl = "perl";
	
# run the script
main();

sub main
{
	# Make a variable to contain the directory list
	my $maclibs;
	
	if ($OS =~ /darwin/)
	{
		# Get a list of files in the client directory
		$maclibs = `ls "$cwd/modules"`;
	}
	
	# If we are running on darwin/MacOSX and the darwin folder does not exist
	if ($OS =~ /darwin/ && $maclibs !~ /darwin/)
	{
		# Display a message prompting the user to download an archive file containing the rsu-settings_mac loader(self contained minimal wxperl) and the wxWidgets libraries.
		print "The rsu-launcher requires extra libraries on MacOSX
(because apple broke their own in 10.5 and up)
So i have packaged a custom loader with a working version of wxWidgets
for use by this script to save you 1 - 2 hours of your life
compiling it yourself.

NOTE: If you want the sourcecode for the loader,
go to $cwd/modules/$OS/rsu-launcher/rsu-launcher-$OS
and add .zip behind the \"rsu-launcher-$OS\" and extract the archive.

Is it ok for me to download these libraries into the client directory?
Answer with yes or no (default = yes):";

		# Wait for users answer
		my $answer = <STDIN>;
		
		# If the user answers no
		if ($answer =~ /(no|n)/i)
		{
			# Exit the script
			exit;
		}
		else
		{
			fetchmaclibs();
		}
	}
	
	# If we are on windows (and the user decided to launch this perl script rather than the .exe)
	if ($OS =~ /MSWin32/)
	{
		# Run the rsu-settings.exe file which is the rsu-settings loader(wxperl loader) for windows
		system "\"$cwd/rsu-launcher.exe\" --script=modules/settings --showcmd=true --usedpar=true &";
	}
	# Else if we are on darwin/MacOSX
	elsif($OS =~ /darwin/)
	{
		# Run the rsu-settings_mac loader(wxperl loader) and point to the location of wxWidgets libraries
		system "\"$cwd/rsu-launcher\" --script=modules/settings --usedpar=true";
	}
	# Else
	else
	{
		# Run the settings module/script directly
		# (as Linux usually have wxWidgets installed or have an easy way to install it)
		system "$perl \"$cwd/modules/settings\"";
	}
	
	exit;
}

#
#---------------------------------------- *** ----------------------------------------
#

sub fetchmaclibs
{
	# Download the perl bundle containing the libraries and extract the archive inside the modules folder
	system "cd \"$cwd/modules\" && curl -o \"$cwd/modules/darwin.tar.gz\" $maclib_url && tar -zxvf \"$cwd/modules/darwin.tar.gz\" && rm \"$cwd/modules/darwin.tar.gz\"";
}

#
#---------------------------------------- *** ----------------------------------------
#

