#!/usr/bin/perl -w

#!/usr/bin/perl -w

# Be strict to avoid messy code
use strict;

# Use FindBin module to get script directory
use FindBin;

# Use custom libs
use lib $FindBin::RealBin."/framework/API";
use lib $FindBin::RealBin."/framework/modules";

# use Cwd to get current working directory
use Cwd;
our $cwd = getcwd;

# Get script directory
our $scriptdir = $FindBin::RealBin;
# Get script filename
our $scriptname = $FindBin::Script;
# Detect the current OS
our $OS = "$^O";
	
# run the script
main();

sub main
{
	# Change dir to the parent directory
	chdir("$scriptdir/..");
	
	# Get the call for the api
	my $apicall = $ARGV[0];
	# Convert to perl module call
	$apicall =~ s/\./::/g;
	
	# Remove $ARGV[0]
	s/$ARGV[0]//g for @ARGV;
	
	# Try to run the module and warn if execution failed
	eval "use $apicall"; warn if $@;
	
	# Exit script
	exit;
}

#
#---------------------------------------- *** ----------------------------------------
#
